---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    component: proxy
spec:
  containers:
    - name: proxy
      env:
        - name: APP_DOMAIN
          value: "kolab.local"
        - name: APP_WEBSITE_DOMAIN
          value: "kolab.local"
        - name: SSL_CERTIFICATE
          value: "/etc/certs/imap.hosted.com.cert"
        - name: SSL_CERTIFICATE_KEY
          value: "/etc/certs/imap.hosted.com.key"
        - name: WEBAPP_BACKEND
          value: "http://webapp:8000"
        - name: MEET_BACKEND
          value: "https://meet:12443"
        - name: ROUNDCUBE_BACKEND
          value: "http://roundcube:8080"
        - name: DAV_BACKEND
          value: "http://dav:11080/dav"
        - name: COLLABORA_BACKEND
          value: "http://collabora:9980"
      image: "image-registry.openshift-image-registry.svc:5000/kolab4-ci/proxy"
      imagePullPolicy: Always
      resources: {}
      securityContext:
        capabilities:
          drop:
            - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - name: docker-certs
          mountPath: /etc/certs
          readOnly: True
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
    - name: pipeline-dockercfg-z2lsh
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pipeline
  serviceAccountName: pipeline
  terminationGracePeriodSeconds: 30
  volumes:
    - name: kube-api-access
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
          - configMap:
              items:
              - key: service-ca.crt
                path: service-ca.crt
              name: openshift-service-ca.crt
    - name: docker-certs
      configMap:
        name: docker-certs
      


