service:
    http_server: "on"
    Health_Check: "on"
    log_level: info
    parsers_file: /etc/fluent-bit/parsers.conf

pipeline:
    inputs:
      - name: tail
        path: /var/log/containers/*.log
        path_key: tailed_path
        exclude_path: "/var/log/containers/fluent*,/var/log/containers/loki*"
        skip_empty_lines: "On"
        tag_regex: (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)\.log$
        tag: "kube.<namespace_name>.<pod_name>.<container_name>"
        multiline.parser: docker, cri

    filters:
      - name: parser
        match: "kube.*"
        key_name: "tailed_path"
        reserve_data: true
        parser: kube-path
      - name: parser
        match: "kube.kolab.roundcube*"
        key_name: "log"
        reserve_data: true
        parser: apache
        parser: logfmt
      - name: parser
        match: "kube.kolab.proxy*"
        key_name: "log"
        reserve_data: true
        parser: nginx

    outputs:
        - name: stdout
          match: '*'
        - name: loki
          host: 'loki.kolab'
          port: 3100
          labels: $pod_name, $namespace_name
