version: '3'
services:
  kurento-media-server2:
    build:
      context: ./docker/kurento-media-server/
    container_name: kolab-kurento-media-server2
    environment:
      - GST_DEBUG=3,Kurento*:4,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4,agnosticbin:4
      - KMS_PORT=8889
    hostname: kurento-media-server.hosted.com
    image: apheleia/kurento-media-server:6.15.0
    network_mode: host
  openvidu:
    build:
      context: ./docker/openvidu-dev/
    privileged: true
    container_name: kolab-openvidu
    depends_on:
      - kurento-media-server
      - kurento-media-server2
    environment:
      - KMS_URIS=["ws://localhost:8888/kurento"]
        #- KMS_URIS=["ws://localhost:8888/kurento", "ws://localhost:8889/kurento"]
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ~/src/openvidu:/src/openvidu/:ro
      - ./docker/openvidu-dev/build/.m2:/root/.m2/
