#!/bin/bash



mysql -h ${DB_HOST:-127.0.0.1} -u root --password=${DB_ROOT_PASSWORD} <<EOF
ALTER USER $DB_HKCCP_USERNAME@'%' IDENTIFIED BY '$DB_HKCCP_PASSWORD';
CREATE USER '$DB_KOLAB_USERNAME'@'%' IF NOT EXISTS IDENTIFIED BY '${DB_KOLAB_PASSWORD}';
ALTER USER $DB_KOLAB_USERNAME@'%' IDENTIFIED BY '$DB_KOLAB_PASSWORD';
FLUSH PRIVILEGES;
EOF
