#!/usr/bin/python3
# Test like so: cat test.mime | /usr/libexec/postfix/kolab_contentfilter_cli -f admin@kolab.local -- noreply@kolab.local
import sys
import logging
import requests
from subprocess import Popen, PIPE

EX_SUCCESS = 0
# Postfix will bounce and not retry
EX_UNAVAILABLE = 69
# Postfix will retry via deferred queue
EX_TEMPFAIL = 75


def get_args():
    try:
        logging.debug("ARGV : %r" % sys.argv)
        cli_from = sys.argv[2].lower()
        cli_to = sys.argv[4:]
        return (cli_from, cli_to)
    except Exception:
        logging.error("Invalid to / from : %r" % sys.argv)
        sys.exit(EX_UNAVAILABLE)


def reinject(content, sender, to):
    command = ["/usr/sbin/sendmail", "-G", "-i", "-f", sender] + to
    stdout = ''
    stderr = ''
    retval = 0
    try:
        process = Popen(command, stdin=PIPE)
        (stdout, stderr) = process.communicate(content.encode())
        retval = process.wait()
        if retval == 0:
            logging.debug("Mail resent via sendmail, stdout: %s, stderr: %s" % (stdout, stderr))
            return EX_SUCCESS
        else:
            raise Exception("retval not zero - %s" % retval)
    except Exception as e:
        print(f"Error re-injecting via {command}")
        logging.error("Exception while re-injecting mail: %s -- stdout:%s, stderr:%s, retval: %s" % (e, stdout, stderr, retval))
        logging.error(f"Commandline used: {command}")
        return EX_TEMPFAIL


if __name__ == "__main__":
    (cli_from, cli_to) = get_args()

    logging.root.handlers = []
    logging.basicConfig(level=logging.ERROR,
                        format='%(asctime)s %(levelname)s %(message)s',
                        filename='/var/log/kolab/postfix-content-filter.log',
                        filemode='a')

    content = ''.join(sys.stdin.readlines())

    try:
        to = ','.join(cli_to)
        request_url = f"SERVICES_HOST/api/webhooks/policy/mail/filter?recipient={to}&sender={cli_from}"
        logging.debug(request_url)
        response = requests.post(
            request_url,
            data=content,
            verify=True
        )

        if response.status_code == 204:
            logging.debug("No changes requested, reinjecting original content.")
            print("Unmodified email")
        elif response.status_code == 200:
            logging.debug("Updating content.")
            print("Modified email")
            content = response.text
        elif response.status_code == 460:
            logging.debug("Rejecting email.")
            print("Rejecting email")
            sys.exit(EX_UNAVAILABLE)
        elif response.status_code == 461:
            logging.debug("Ignoring email.")
            print("Dropping email")
            sys.exit(EX_SUCCESS)
        else:
            logging.warning(f"Unknown status code {response.status_code}.")
            print(f"Unknown status code {response.status_code}")
            sys.exit(EX_TEMPFAIL)

    # pylint: disable=broad-except
    except Exception:
        logging.warning("Request failed.")
        print("Request failed")
        sys.exit(EX_TEMPFAIL)

    sys.exit(reinject(content, cli_from, cli_to))
