---
- name: Check if the file already exists
  stat:
    path: /etc/letsencrypt/live/{{ hostname }}
  register: stat_result

- name: certbot
  block:
    - name: stop firewall
      ansible.builtin.service:
        name: firewalld
        state: stopped

    - name: Create letsencrypt certificate
      shell: certonly --standalone -d {{ hostname }} --staple-ocsp -m test@{{ hostname }} --agree-tos
      args:
        creates: /etc/letsencrypt/live/{{ hostname }}

    - name: chmod letsencrypt certificate
      shell: chmod 755 /etc/letsencrypt/{live, archive}

    - name: start firewall
      ansible.builtin.service:
        name: firewalld
        state: started

  when: not stat_result.stat.exists
