apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fedora-s2i-core
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: fedora-s2i-core:latest
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://git.kolab.org/source/kolab-s2i-core.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fedora:37
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
