apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: fedora
  name: fedora
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: docker.io/fedora:37
    from:
      kind: DockerImage
      name: docker.io/fedora:37
    generation: 2
    name: "37"
    referencePolicy:
      type: Local
