kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: kolab-dev
  labels:
    template: redis-ephemeral-template
    template.openshift.io/template-instance-owner: 43c18c6d-fbf8-4b42-9973-8b076cb68a1c
  annotations:
    template.openshift.io/expose-uri: 'redis://{.spec.clusterIP}:{.spec.ports[?(.name=="redis")].port}'
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  selector:
    name: redis
